#!/bin/sh -eu

err() {
    echo "ERR: $@"
    exit 1
}

[ "$(id -u)" -eq 0 ] || err "Must run as root"

[ "$#" -ge 1 ] || err "Must at least specify host: $0 <host>"

ssh -R 5900:localhost:5900 \
    -o PasswordAuthentication=no \
    -o KbdInteractiveAuthentication=no \
    -o HostbasedAuthentication=no \
    -o GSSAPIAuthentication=no \
    -o PubkeyAuthentication=yes \
    -o StrictHostKeyChecking=accept-new \
    -i "${SNAP_COMMON}/id_rsa" \
    "$@"
