name: ssh-port-forward
base: core20
version: '0.1'
summary: Create an SSH reverse port forward
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: strict

parts:
  scripts:
    plugin: dump
    source: ./scripts
    organize:
      '*': bin/

  debs:
    plugin: nil
    stage-packages:
      - openssh-client

apps:
  ssh-port-forward:
    command: bin/port-forward
    plugs:
      - network
      - network-bind
  pubkey:
    command: bin/pubkey
